import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { JournalProvider } from '@/context/JournalContext'
import Navbar from "./components/navbar";
import Footer from "./components/footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex-grow">
        <div className="flex flex-col min-h-screen">
        <Navbar/>
        <JournalProvider>
          {children}
        </JournalProvider>
        
        </div>
        <Footer/>
      </body>
    </html>
  );
}
